# Generated by Django 2.2.4 on 2020-02-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200203_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cardholder',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
    ]
