# Generated by Django 2.2.4 on 2020-02-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_customer_cardholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='license_key',
            field=models.CharField(default='asdfghjkl', max_length=20),
            preserve_default=False,
        ),
    ]
