# Generated by Django 2.2.4 on 2020-02-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200228_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_id',
            field=models.CharField(default='asdfghjkl', max_length=18, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
