# Generated by Django 2.2.4 on 2020-03-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_customer_cardholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='license_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.License'),
        ),
    ]
