# Generated by Django 2.2.4 on 2020-03-29 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20200322_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 13, 19, 54, 148087)),
            preserve_default=False,
        ),
    ]
